# This is a basic workflow to help you get started with Actions

name: Build & Publish documentation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build the documentation
  build:
    runs-on: windows-latest # Required by DocFX
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # with:
        #   submodules: true

      - name: Install DocFX
        run: choco install -y docfx

      - name: Build
        run: docfx "RPG Project/Documentation/docfx.json"

      # Upload the generated documentation
      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path: "RPG Project/_site" # Must equals the 'build.dest' value on your docfx.json

# Deploy the generated documentation to the gh-pages branch
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # with:
        #   submodules: true

      # Download the generated documentation
      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: _site

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: _site
